### ISSUE TITLE
Data on Industrial Edge device is not persistent using example docker compose file

### ISSUE THREAD

**Issue by stefschm** [mendix/docker-mendix-buildpack#137]
Using the example docker compose configuration is working but the data is stored only not persistent in working memory. Could you please provide an example which enables persistent data storeage?

```
myapp:
  environment:
    ADMIN_PASSWORD: *******
    DATABASE_ENDPOINT: 'jdbc:hsqldb:file:~/data/database/db:mem:mendix'
    MXRUNTIME_DatabaseType: HSQLDB
    MXRUNTIME_DatabaseJdbcUrl: 'jdbc:hsqldb:file:~/data/database/db:mem:mendix'
    IEM_CONFIG_PATH: /cfg-data
  image: 'sample_app:1.1'
  volumes:
    - './publish/:/publish/'
    - './cfg-data/:/cfg-data/'
  mem_limit: 1gb
  restart: unless-stopped
  ports:
    - '60000:8080'
```
